name: project_x
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - dataclasses=0.8=pyhc8e2a94_3
  - pytorch=1.9.0=py3.9_cuda11.1_cudnn8.0.5_0
  - pytorch-lightning=1.4.5=pyhd8ed1ab_0
  - torchaudio=0.9.0=py39
  - torchmetrics=0.5.1=pyhd8ed1ab_0
  - torchvision=0.10.0=py39_cu111
